version: '3.9'
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: 200lab
      POSTGRES_DB: crawler
    ports:
      - "5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.2.4-alpine
    environment:
      - "REDIS_ARGS=--requirepass 200lab"
    ports:
      - "6379"
    networks:
      - intranet
  consumer:
    build: 
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: 200lab
      POSTGRES_DNS: postgresql://crawler:200lab@postgres:5432/crawler?sslmode=disable
    depends_on:
      - postgres
      - redis
    entrypoint:
      [   
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]   
    command: [ "/app/consumer" ]
    networks:
      - intranet
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: 200lab
    depends_on:
      - redis
    networks:
      - intranet
networks:
  intranet:
    name: crawler_network
