# build stage
FROM golang:1.21.6-alpine3.19 AS build
WORKDIR /app
COPY ./crawler . 
RUN go build -o crawler .

# operational stage
FROM alpine:3.19 AS operation
WORKDIR /app
COPY --from=build /app/crawler .
CMD ["/app/crawler"]
